### ISSUE TITLE
Add object properties meta and object properties value table

### ISSUE THREAD

**Issue by mothaibatacungmua** [mothaibatacungmua/project-fd#1]
**Is your feature request related to a problem? Please describe.**
Need to mechanism to hold universal any properties of object. Two table have to control:

- Table object properties meta (`obj_prop_meta`) contains meta to describe object properties.
- Table object properties value (`obj_prop_value`) contains values from crawling or computing.

**Task**:

- [ ] Create `obj_prop_meta` and `obj_prop_value` tables.
- [ ] Fetch objects on these tables.
- [ ] Search on these tables by name, group and description.
- [ ] Query mechanism by YAML template

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
